from __future__ import annotations


COST_FIELDNAMES = {
	"rate",
	"amount",
	"base_amount",
	"net_amount",
	"base_net_amount",
	"current_amount",
	"valuation_rate",
	"current_valuation_rate",
	"incoming_rate",
	"last_purchase_rate",
	"purchase_rate",
	"standard_rate",
	"stock_uom_rate",
	"stock_value",
	"stock_value_difference",
	"valuation_amount",
	"basic_amount",
	"total_incoming_value",
	"total_outgoing_value",
	"value_difference",
	"base_net_rate",
	"net_rate",
	"base_rate",
	"basic_rate",
	"rm_supp_cost",
	"landed_cost_voucher_amount",
	"sales_incoming_rate",
	"gross_profit",
	"gross_profit_percent",
	"base_price_list_rate",
	"price_list_rate",
}


COST_FIELD_LABEL_KEYWORDS = [
	"valuation",
	"valuation rate",
	"current valuation",
	"incoming rate",
	"purchase rate",
	"last purchase",
	"stock value",
	"incoming value",
	"outgoing value",
	"value difference",
	"stock uom rate",
	"gross profit",
	"cost price",
	"cost rate",
	"additional cost",
	"landed cost",
]
