from __future__ import annotations

import csv
import html
import io
import json
from typing import Any

import frappe
from frappe import _
from frappe.utils import cint
from frappe.utils.pdf import get_pdf
from frappe.utils.xlsxutils import make_xlsx

from retailedge.reporting_actions import get_report_dataset
from retailedge.reporting_capabilities import require_report_action

MIME_TYPES = {
    "xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "csv": "text/csv; charset=utf-8",
    "pdf": "application/pdf",
}
PRESENTATION_KEYS = (
    "include_summary",
    "include_filters",
    "include_charts",
    "include_letterhead",
    "include_title",
    "include_generated_metadata",
    "include_totals",
)
MAX_CURRENT_PAGE_LENGTH = 200


def _json_dict(value: str | dict | None) -> dict:
    if not value:
        return {}
    if isinstance(value, dict):
        return dict(value)
    parsed = json.loads(value)
    if not isinstance(parsed, dict):
        frappe.throw(_("Report export options must be a JSON object."))
    return parsed


def _normalize_options(options: str | dict | None) -> dict:
    value = _json_dict(options)
    file_format = str(value.get("format") or "xlsx").lower()
    if file_format not in MIME_TYPES:
        frappe.throw(_("Unsupported report export format."))
    scope = str(value.get("scope") or "all_filtered")
    if scope not in {"current_page", "all_filtered"}:
        frappe.throw(_("Unsupported report export scope."))
    normalized = {
        "format": file_format,
        "scope": scope,
        "columns": [str(item) for item in (value.get("columns") or []) if item],
        "orientation": str(value.get("orientation") or "auto").lower(),
        "repeat_table_headings": value.get("repeat_table_headings") is not False,
    }
    for key in PRESENTATION_KEYS:
        normalized[key] = bool(value.get(key))
    normalized["raw_table_only"] = not any(normalized[key] for key in PRESENTATION_KEYS)
    return normalized


def _column_dict(column: Any, index: int) -> dict:
    if isinstance(column, dict):
        return {
            **column,
            "label": column.get("label") or column.get("fieldname") or f"Column {index + 1}",
            "fieldname": column.get("fieldname") or column.get("key") or f"column_{index + 1}",
        }
    return {"label": f"Column {index + 1}", "fieldname": f"column_{index + 1}", "fieldtype": "Data"}


def _normalise_dataset(dataset: dict) -> tuple[list[dict], list[dict], list[dict]]:
    columns = [_column_dict(column, index) for index, column in enumerate(dataset.get("columns") or [])]
    rows = list(dataset.get("rows") or [])
    normalised_rows: list[dict] = []
    for row in rows:
        if isinstance(row, dict):
            normalised_rows.append(row)
        elif isinstance(row, (list, tuple)):
            normalised_rows.append({column["fieldname"]: row[index] if index < len(row) else None for index, column in enumerate(columns)})
    summary = [item for item in (dataset.get("summary") or []) if isinstance(item, dict)]
    return columns, normalised_rows, summary


def _select_columns(columns: list[dict], selected: list[str]) -> list[dict]:
    visible = [column for column in columns if not column.get("hidden")]
    if not selected:
        return visible
    by_name = {column.get("fieldname"): column for column in visible if column.get("fieldname")}
    return [by_name[fieldname] for fieldname in selected if fieldname in by_name]


def _slice_rows(rows: list[dict], options: dict, start: int, page_length: int) -> list[dict]:
    if options["scope"] != "current_page":
        return rows
    start = max(0, cint(start))
    page_length = min(MAX_CURRENT_PAGE_LENGTH, max(1, cint(page_length) or 50))
    return rows[start : start + page_length]


def _safe(value: Any) -> Any:
    if value is None:
        return ""
    if isinstance(value, (str, int, float, bool)):
        return value
    return str(value)


def _filter_rows(filters: dict) -> list[list[Any]]:
    return [[str(key).replace("_", " ").title(), _safe(value)] for key, value in filters.items() if value not in (None, "", [])]


def _summary_rows(summary: list[dict]) -> list[list[Any]]:
    return [[item.get("label") or _("Metric"), _safe(item.get("value"))] for item in summary]


def _table_matrix(title: str, filters: dict, columns: list[dict], rows: list[dict], summary: list[dict], options: dict) -> tuple[list[list[Any]], int]:
    matrix: list[list[Any]] = []
    if options["include_title"]:
        matrix.append([title])
    if options["include_generated_metadata"]:
        matrix.append([_("Generated"), frappe.utils.now_datetime().isoformat(sep=" ", timespec="seconds")])
        matrix.append([_("Generated By"), frappe.session.user])
    if options["include_filters"]:
        matrix.extend(_filter_rows(filters))
    if options["include_summary"]:
        matrix.extend(_summary_rows(summary))
    if matrix:
        matrix.append([])
    header_index = len(matrix)
    matrix.append([column.get("label") or column["fieldname"] for column in columns])
    for row in rows:
        matrix.append([_safe(row.get(column["fieldname"])) for column in columns])
    return matrix, header_index


def _csv_bytes(matrix: list[list[Any]]) -> bytes:
    stream = io.StringIO(newline="")
    writer = csv.writer(stream)
    for row in matrix:
        writer.writerow([_safe(value) for value in row])
    return stream.getvalue().encode("utf-8-sig")


def _xlsx_bytes(matrix: list[list[Any]], title: str, header_index: int, include_filters: bool) -> bytes:
    stream = make_xlsx(matrix, (title or "Report")[:31], header_index=header_index, has_filters=include_filters)
    return stream.getvalue()


def _letterhead_html() -> str:
    company = frappe.defaults.get_user_default("Company") or frappe.defaults.get_global_default("company")
    name = frappe.get_cached_value("Company", company, "default_letter_head") if company else None
    if not name:
        return ""
    letterhead = frappe.get_doc("Letter Head", name)
    if not letterhead.has_permission("read"):
        return ""
    return letterhead.content or ""


def _report_html(title: str, filters: dict, columns: list[dict], rows: list[dict], summary: list[dict], options: dict) -> str:
    parts = ["<!doctype html><html><head><meta charset='utf-8'><style>"]
    parts.append("@page{margin:12mm}body{font-family:Arial,sans-serif;color:#172033;font-size:9pt}h1{font-size:16pt;margin:0 0 8px}.meta,.filters{margin:0 0 10px}.summary{display:flex;gap:8px;flex-wrap:wrap;margin:0 0 10px}.card{border:1px solid #dfe5ef;border-radius:6px;padding:6px 9px}.card b{display:block;font-size:11pt}table{width:100%;border-collapse:collapse}th,td{border:1px solid #dfe5ef;padding:5px;vertical-align:top}th{background:#f3f5f8;text-align:left}")
    if options.get("repeat_table_headings", True):
        parts.append("thead{display:table-header-group}")
    parts.append("</style></head><body>")
    if options.get("include_letterhead"):
        parts.append(_letterhead_html())
    if options.get("include_title", True):
        parts.append(f"<h1>{html.escape(title)}</h1>")
    if options.get("include_generated_metadata", True):
        parts.append(f"<div class='meta'>{html.escape(_('Generated'))}: {html.escape(str(frappe.utils.now_datetime()))} · {html.escape(frappe.session.user)}</div>")
    if options.get("include_filters"):
        values = " · ".join(f"{html.escape(str(key).replace('_', ' ').title())}: {html.escape(str(value))}" for key, value in filters.items() if value not in (None, "", []))
        if values:
            parts.append(f"<div class='filters'>{values}</div>")
    if options.get("include_summary") and summary:
        parts.append("<div class='summary'>")
        for item in summary:
            parts.append(f"<div class='card'>{html.escape(str(item.get('label') or _('Metric')))}<b>{html.escape(str(_safe(item.get('value'))))}</b></div>")
        parts.append("</div>")
    parts.append("<table><thead><tr>")
    for column in columns:
        parts.append(f"<th>{html.escape(str(column.get('label') or column['fieldname']))}</th>")
    parts.append("</tr></thead><tbody>")
    for row in rows:
        parts.append("<tr>")
        for column in columns:
            parts.append(f"<td>{html.escape(str(_safe(row.get(column['fieldname']))))}</td>")
        parts.append("</tr>")
    parts.append("</tbody></table></body></html>")
    return "".join(parts)


def _filename(report_key: str, file_format: str) -> str:
    safe = "-".join(part for part in str(report_key or "report").replace("_", "-").split("-") if part)
    return f"RetailEdge-{safe or 'report'}.{file_format}"


def _set_download_response(content: bytes, report_key: str, file_format: str) -> None:
    if not content:
        frappe.throw(_("The generated report export is empty."))
    frappe.local.response.filename = _filename(report_key, file_format)
    frappe.local.response.filecontent = content
    frappe.local.response.type = "download"
    frappe.local.response.content_type = MIME_TYPES[file_format]
    frappe.local.response.display_content_as = "attachment"


@frappe.whitelist()
def download_report(
    report_key: str,
    filters: str | dict | None = None,
    options: str | dict | None = None,
    start: int | str = 0,
    page_length: int | str = 50,
):
    filters = _json_dict(filters)
    options = _normalize_options(options)
    require_report_action(report_key, action="export", company=filters.get("company"), branch=filters.get("branch"))
    dataset = get_report_dataset(report_key, filters)
    columns, rows, summary = _normalise_dataset(dataset)
    columns = _select_columns(columns, options["columns"])
    rows = _slice_rows(rows, options, cint(start), cint(page_length))
    title = str(dataset.get("title") or report_key.replace("-", " ").title())
    matrix, header_index = _table_matrix(title, filters, columns, rows, summary, options)
    file_format = options["format"]
    if file_format == "csv":
        content = _csv_bytes(matrix)
    elif file_format == "xlsx":
        content = _xlsx_bytes(matrix, title, header_index, options["include_filters"])
    else:
        pdf_html = _report_html(title, filters, columns, rows, summary, options)
        content = get_pdf(pdf_html, options={"orientation": "Landscape" if options["orientation"] == "landscape" else "Portrait"})
    _set_download_response(content, report_key, file_format)


@frappe.whitelist()
def get_report_print_html(
    report_key: str,
    filters: str | dict | None = None,
    start: int | str = 0,
    page_length: int | str = 50,
) -> dict:
    filters = _json_dict(filters)
    require_report_action(report_key, action="print", company=filters.get("company"), branch=filters.get("branch"))
    dataset = get_report_dataset(report_key, filters)
    columns, rows, summary = _normalise_dataset(dataset)
    options = {
        "include_title": True,
        "include_generated_metadata": True,
        "include_filters": True,
        "include_summary": True,
        "include_letterhead": True,
        "repeat_table_headings": True,
    }
    title = str(dataset.get("title") or report_key.replace("-", " ").title())
    return {"html": _report_html(title, filters, _select_columns(columns, []), rows, summary, options), "title": title}
