<template>
	<div v-if="!edgeUIValid" class="project-fallback">
		<strong>Project Operations could not start.</strong>
		<span>Missing EdgeSuite UI components: {{ missingComponents.join(", ") }}</span>
	</div>
	<EdgeAppShell v-else product="RetailEdge" title="Project Operations" :tenantName="context.company || projectCompany || ''" :branchName="branch" :userName="userName" :menuItems="menuItems" activeRoute="/app/project-operations" :hideNativeSidebar="true" @navigate="handleNavigation">
		<section class="project-page">
			<header class="project-hero">
				<div><div class="project-eyebrow">Projects & Funds</div><h2>{{ context.project_name || "Project Operations" }}</h2><p>Operational and financial visibility over ERPNext Project, Task, Budget, Payment Entry and native project accounting dimensions.</p></div>
				<div class="hero-actions">
					<button class="edge-secondary-button" type="button" :disabled="!project" @click="openProject">Open ERPNext Project</button>
					<button class="edge-secondary-button" type="button" :disabled="!project" @click="openProjectTasks">Open Tasks</button>
					<button class="edge-secondary-button" type="button" :disabled="!project || !activity.can_create_task" @click="newTask">New Task</button>
					<button class="edge-secondary-button" type="button" :disabled="!project || !budget.available || !budget.readable" @click="openProjectBudgets">Open Budgets</button>
					<button class="edge-secondary-button" type="button" :disabled="!project || !budget.can_create_budget" @click="newBudget">New Budget</button>
					<button class="edge-secondary-button" type="button" :disabled="!project" @click="openCostDialog">Record Project Cost</button>
					<button class="edge-primary-button" type="button" :disabled="!project || !context.customer" @click="openReceiptDialog">Record Project Receipt</button>
				</div>
			</header>

			<section class="project-panel"><div class="filter-grid"><EdgeLinkField v-model="project" :selectedLabel="projectLabel" label="Project" required placeholder="Search projects" :searcher="projectSearch" @select="onProjectSelected" @clear="clearProject" /><EdgeLinkField v-model="branch" :selectedLabel="branchLabel" label="Branch" placeholder="Optional branch scope" :disabled="!projectCompany" :searcher="branchSearch" @select="onBranchSelected" @clear="clearBranch" /><div class="filter-action"><button class="edge-primary-button" type="button" :disabled="loading || !project" @click="loadContext">{{ loading ? "Refreshing…" : "Refresh" }}</button></div></div></section>

			<div v-if="error" class="project-error">{{ error }}</div>
			<div v-else-if="loading" class="project-state">Loading project operations…</div>
			<template v-else-if="project && context.project">
				<div v-if="context.scope?.branch_scope_note" class="scope-note"><strong>Scope:</strong> {{ context.scope.branch_scope_note }}</div>
				<div class="project-cards">
					<article class="metric-card"><span>Sales Order Value</span><strong>{{ money(context.sales_order_value) }}</strong></article><article class="metric-card"><span>Billed</span><strong>{{ money(context.billed_amount) }}</strong></article><article class="metric-card"><span>Project Cash In</span><strong>{{ money(context.project_cash_in) }}</strong></article><article class="metric-card"><span>Project Cash Out</span><strong>{{ money(context.project_cash_out) }}</strong></article><article class="metric-card"><span>Net Project-linked Cash</span><strong>{{ money(context.net_project_cash) }}</strong></article><article class="metric-card"><span>Tracked Cost</span><strong>{{ money(context.tracked_cost) }}</strong></article><article class="metric-card"><span>Gross Margin</span><strong>{{ money(context.gross_margin) }}</strong></article><article class="metric-card"><span>Progress</span><strong>{{ context.percent_complete || 0 }}%</strong></article><article class="metric-card"><span>Open Tasks</span><strong>{{ activity.open_count || 0 }}</strong></article><article class="metric-card"><span>Milestones</span><strong>{{ activity.milestone_count || 0 }}</strong></article><article class="metric-card"><span>Submitted Project Budget</span><strong>{{ money(budget.submitted_budget) }}</strong></article>
				</div>

				<section class="project-panel"><div class="panel-head"><div><h3>Project Summary</h3><p>ERPNext Project remains authoritative for project identity, costing, billing and margin.</p></div></div><div class="summary-grid"><div><span>Project</span><strong>{{ context.project }}</strong></div><div><span>Status</span><strong>{{ context.status || "—" }}</strong></div><div><span>Customer</span><strong>{{ context.customer || "—" }}</strong></div><div><span>Company</span><strong>{{ context.company || "—" }}</strong></div><div><span>Cost Center</span><strong>{{ context.cost_center || "—" }}</strong></div><div><span>Unapplied Receipts</span><strong>{{ money(context.unallocated_receipts) }}</strong></div><div><span>Purchase Cost</span><strong>{{ money(context.purchase_cost) }}</strong></div><div><span>Consumed Material Cost</span><strong>{{ money(context.consumed_material_cost) }}</strong></div><div><span>Timesheet Cost</span><strong>{{ money(context.timesheet_cost) }}</strong></div></div><p class="panel-note">Tracked Cost is the transparent sum of these ERPNext Project cost components. It is not a separate RetailEdge accounting balance.</p></section>

				<section class="project-panel"><div class="panel-head"><div><h3>Tasks & Milestones</h3><p>{{ activity.scope_note || "ERPNext Task remains the operational source of truth." }}</p></div><span>{{ activity.task_count || 0 }} tasks</span></div><div v-if="!activity.tasks?.length" class="project-state">No ERPNext Tasks are linked to this Project.</div><div v-else class="table-wrap"><table class="project-table"><thead><tr><th>Task</th><th>Type</th><th>Status</th><th>Priority</th><th class="num">Progress</th><th>Expected End</th></tr></thead><tbody><tr v-for="row in activity.tasks" :key="row.name"><td><button class="link-button" @click="openTask(row.name)">{{ row.subject }}</button></td><td>{{ row.is_milestone ? "Milestone" : (row.is_group ? "Group" : "Task") }}</td><td>{{ row.status || "—" }}</td><td>{{ row.priority || "—" }}</td><td class="num">{{ row.progress || 0 }}%</td><td>{{ row.expected_end || "—" }}</td></tr></tbody></table></div></section>

				<section class="project-panel"><div class="panel-head"><div><h3>Project Budget Governance</h3><p>{{ budget.scope_note || budget.policy || "ERPNext Budget remains the governance authority." }}</p></div><span>{{ budget.budget_count || 0 }} budgets</span></div><div v-if="budget.available && !budget.readable" class="project-state">You do not have permission to read ERPNext Budgets for this Project.</div><div v-else-if="!budget.budgets?.length" class="project-state">No ERPNext Project Budgets found.</div><div v-else class="table-wrap"><table class="project-table"><thead><tr><th>Budget</th><th>Account</th><th>Status</th><th>Fiscal Period</th><th class="num">Amount</th><th>Controls</th></tr></thead><tbody><tr v-for="row in budget.budgets" :key="row.name"><td><button class="link-button" @click="openBudget(row.name)">{{ row.name }}</button></td><td>{{ row.account || "—" }}</td><td>{{ row.status }}</td><td>{{ row.from_fiscal_year }}<span v-if="row.to_fiscal_year && row.to_fiscal_year !== row.from_fiscal_year"> – {{ row.to_fiscal_year }}</span></td><td class="num">{{ money(row.budget_amount) }}</td><td>{{ row.controls?.length ? row.controls.join(" · ") : "No spend-stop/warn control configured" }}</td></tr></tbody></table></div><p class="panel-note">ERPNext Budget Stop/Warn/Ignore controls remain authoritative for project purchasing and expense governance; RetailEdge does not bypass them.</p></section>

				<section class="project-panel"><div class="panel-head"><div><h3>Project Transaction Timeline</h3><p>Read-only view of permitted ERPNext Sales Orders, Sales Invoices, Purchase Invoices, Expense Claims and Stock Entries linked to this Project. Cancelled documents are excluded.</p></div><span>{{ context.timeline_count || 0 }} records</span></div><div v-if="!context.timeline?.length" class="project-state">No project-linked operational documents found for the current scope.</div><div v-else class="table-wrap"><table class="project-table"><thead><tr><th>Date</th><th>Type</th><th>Document</th><th>Status</th><th>Party</th><th class="num">Amount</th></tr></thead><tbody><tr v-for="row in context.timeline" :key="`${row.doctype}-${row.name}`"><td>{{ row.date || "—" }}</td><td>{{ row.label }}</td><td><button class="link-button" @click="openTimelineDoc(row)">{{ row.name }}</button></td><td>{{ row.status || "—" }}</td><td>{{ row.party || "—" }}</td><td class="num">{{ row.amount ? money(row.amount) : "—" }}</td></tr></tbody></table></div></section>
				<section class="project-panel"><div class="panel-head"><div><h3>Project Cash In</h3><p>Submitted incoming ERPNext Payment Entries explicitly linked to this Project. This is cash movement, not revenue recognition.</p></div></div><div v-if="!context.project_cash_in_rows?.length" class="project-state">No submitted project-linked incoming payments found.</div><div v-else class="table-wrap"><table class="project-table"><thead><tr><th>Payment</th><th>Date</th><th>Party Type</th><th>Party</th><th>Mode</th><th class="num">Received</th><th class="num">Unapplied</th></tr></thead><tbody><tr v-for="row in context.project_cash_in_rows" :key="row.name"><td><button class="link-button" @click="openPayment(row.name)">{{ row.name }}</button></td><td>{{ row.posting_date }}</td><td>{{ row.party_type || "—" }}</td><td>{{ row.party || "—" }}</td><td>{{ row.mode_of_payment || "—" }}</td><td class="num">{{ money(row.received_amount) }}</td><td class="num">{{ money(row.unallocated_amount) }}</td></tr></tbody></table></div></section>
				<section class="project-panel"><div class="panel-head"><div><h3>Project Cash Out</h3><p>Submitted outgoing ERPNext Payment Entries explicitly linked to this Project. This is cash movement, not an expense/P&amp;L measure.</p></div></div><div v-if="!context.project_cash_out_rows?.length" class="project-state">No submitted project-linked outgoing payments found.</div><div v-else class="table-wrap"><table class="project-table"><thead><tr><th>Payment</th><th>Date</th><th>Party Type</th><th>Party</th><th>Mode</th><th class="num">Paid</th></tr></thead><tbody><tr v-for="row in context.project_cash_out_rows" :key="row.name"><td><button class="link-button" @click="openPayment(row.name)">{{ row.name }}</button></td><td>{{ row.posting_date }}</td><td>{{ row.party_type || "—" }}</td><td>{{ row.party || "—" }}</td><td>{{ row.mode_of_payment || "—" }}</td><td class="num">{{ money(row.paid_amount) }}</td></tr></tbody></table></div></section>
				<div class="accounting-note"><strong>Accounting safety:</strong> Project Funds is a derived management view. ERPNext Project, Task, Budget and project-linked native documents remain the source of truth; RetailEdge does not maintain a project wallet, task ledger, budget ledger or separate accounting ledger. Project Cash In/Out is not a bank balance, revenue, expense or profit measure.</div>
			</template>
		</section>
	</EdgeAppShell>
</template>

<script>
const REQUIRED_COMPONENTS = ["EdgeAppShell", "EdgeLinkField"];
function runtimeComponents() { return window.EdgeSuiteUI?.components || {}; }
function callMethod(method, args = {}) { return new Promise((resolve, reject) => frappe.call({ method, args, callback: (r) => resolve(r.message || {}), error: reject })); }
function errorMessage(error, fallback) { return error?.message || error?.exc || error?.exception || fallback; }
export default {
	name: "ProjectOperations", components: Object.fromEntries(REQUIRED_COMPONENTS.map((name) => [name, runtimeComponents()[name]])),
	data() { return { edgeUIValid: true, missingComponents: [], loading: false, error: "", project: "", projectLabel: "", projectCompany: "", branch: "", branchLabel: "", context: {}, activity: {}, budget: {}, menuItems: [], userName: "" }; },
	created() { const components = runtimeComponents(); this.missingComponents = REQUIRED_COMPONENTS.filter((name) => !components[name]); this.edgeUIValid = this.missingComponents.length === 0; }, mounted() { this.loadNavigation(); },
	methods: {
		async loadNavigation() { try { const navigation = typeof window.retailedgeGetBusinessHubContext === "function" ? await window.retailedgeGetBusinessHubContext() : await callMethod("retailedge.edgesuite_ui.get_retailedge_business_hub_context"); this.menuItems = this.mapNavigationGroups(navigation.navigation_groups || []); this.userName = navigation.user_name || navigation.context?.user_name || ""; } catch (error) { this.error = errorMessage(error, "Failed to load Project Operations navigation."); } },
		async projectSearch(txt) { const result = await callMethod("retailedge.project_search.search_projects", { txt, limit: 20 }); return Array.isArray(result) ? result : []; }, async branchSearch(txt) { if (!this.projectCompany) return []; const result = await callMethod("retailedge.project_search.search_project_branches", { txt, company: this.projectCompany, limit: 20 }); return Array.isArray(result) ? result : []; },
		onProjectSelected(option) { this.project = option.value; this.projectLabel = option.label || option.value; this.projectCompany = option.company || ""; this.branch = ""; this.branchLabel = ""; this.context = {}; this.activity = {}; this.budget = {}; this.loadContext(); }, clearProject() { this.project = ""; this.projectLabel = ""; this.projectCompany = ""; this.branch = ""; this.branchLabel = ""; this.context = {}; this.activity = {}; this.budget = {}; this.error = ""; }, onBranchSelected(option) { this.branch = option.value; this.branchLabel = option.label || option.value; this.loadContext(); }, clearBranch() { this.branch = ""; this.branchLabel = ""; if (this.project) this.loadContext(); },
		async loadContext() { if (!this.project) return; this.loading = true; this.error = ""; try { const [funds, activity, budget] = await Promise.all([callMethod("retailedge.project_operations.get_project_funds_context", { project: this.project, branch: this.branch || null }), callMethod("retailedge.project_activity.get_project_activity_context", { project: this.project, limit: 200 }), callMethod("retailedge.project_budget.get_project_budget_context", { project: this.project, limit: 100 })]); this.context = funds; this.activity = activity; this.budget = budget; this.projectCompany = this.context.company || this.projectCompany; if (this.branch && !this.branchLabel) this.branchLabel = this.branch; } catch (error) { this.context = {}; this.activity = {}; this.budget = {}; this.error = errorMessage(error, "Project operations failed to load."); } finally { this.loading = false; } },
		openReceiptDialog() { const dialog = new frappe.ui.Dialog({ title: __("Record Project Receipt"), fields: [ { fieldname: "project", fieldtype: "Data", label: __("Project"), default: this.project, read_only: 1 }, { fieldname: "customer", fieldtype: "Data", label: __("Customer"), default: this.context.customer, read_only: 1 }, { fieldname: "company", fieldtype: "Data", label: __("Company"), default: this.context.company, read_only: 1 }, { fieldname: "branch", fieldtype: "Data", label: __("Branch"), default: this.branch || "", read_only: 1 }, { fieldname: "posting_date", fieldtype: "Date", label: __("Posting Date"), default: frappe.datetime.get_today(), reqd: 1 }, { fieldname: "mode_of_payment", fieldtype: "Link", options: "Mode of Payment", label: __("Mode of Payment"), reqd: 1 }, { fieldname: "amount", fieldtype: "Currency", label: __("Amount"), reqd: 1 }, { fieldname: "reference_no", fieldtype: "Data", label: __("Reference No") }, { fieldname: "reference_date", fieldtype: "Date", label: __("Reference Date") }, { fieldname: "remarks", fieldtype: "Small Text", label: __("Remarks") } ], primary_action_label: __("Create Draft Payment"), primary_action: async (values) => { try { const result = await callMethod("retailedge.project_receipts.create_project_receipt_draft", { values }); dialog.hide(); frappe.show_alert({ message: __("Project receipt draft created."), indicator: "green" }); if (result.name) frappe.set_route("Form", "Payment Entry", result.name); } catch (error) { frappe.msgprint({ title: __("Could not create project receipt"), message: errorMessage(error, "Project receipt draft could not be created."), indicator: "red" }); } } }); dialog.show(); },
		async openCostDialog() { try { const result = await callMethod("retailedge.project_expense_routing.get_project_expense_routes", { project: this.project }); const routes = result.routes || []; if (!routes.length) { frappe.msgprint(__("You do not have permission to create any supported project cost document.")); return; } const optionMap = Object.fromEntries(routes.map((route) => [route.label, route])); const dialog = new frappe.ui.Dialog({ title: __("Record Project Cost"), fields: [ { fieldname: "route", fieldtype: "Select", label: __("Cost Type"), options: routes.map((route) => route.label).join("\n"), reqd: 1 }, { fieldname: "policy", fieldtype: "HTML", options: `<div class="text-muted small">${frappe.utils.escape_html(result.policy || "")}</div>` } ], primary_action_label: __("Open Native Entry"), primary_action: (values) => { const route = optionMap[values.route]; if (!route) return; dialog.hide(); frappe.new_doc(route.doctype, route.defaults || {}); } }); dialog.show(); } catch (error) { frappe.msgprint({ title: __("Could not load project cost options"), message: errorMessage(error, "Project cost routes could not be loaded."), indicator: "red" }); } },
		openProject() { if (this.project) frappe.set_route("Form", "Project", this.project); }, openProjectTasks() { if (this.project) frappe.set_route("List", "Task", { project: this.project }); }, newTask() { if (this.project && this.activity.can_create_task) frappe.new_doc("Task", { project: this.project }); }, openTask(name) { if (name) frappe.set_route("Form", "Task", name); }, openProjectBudgets() { if (this.project && this.budget.readable) frappe.set_route("List", "Budget", { budget_against: "Project", project: this.project, company: this.context.company }); }, newBudget() { if (this.project && this.budget.can_create_budget) frappe.new_doc("Budget", { budget_against: "Project", project: this.project, company: this.context.company }); }, openBudget(name) { if (name) frappe.set_route("Form", "Budget", name); }, openPayment(name) { frappe.set_route("Form", "Payment Entry", name); }, openTimelineDoc(row) { if (row?.doctype && row?.name) frappe.set_route("Form", row.doctype, row.name); }, money(value) { return format_currency(Number(value || 0), this.context.currency || undefined); },
		mapNavigationGroups(groups) { return (groups || []).map((group) => ({ ...group, items: (group.items || []).map((item) => ({ ...item, route: this.routeForItem(item) })) })); }, routeForItem(item) { if (item.target_type === "Page") return `/app/${item.target}`; if (item.target_type === "Report") return `/app/query-report/${encodeURIComponent(item.target)}`; if (item.target_type === "DocType") return `/app/${String(item.target || "").toLowerCase().replace(/\s+/g, "-")}`; return item.target || ""; }, handleNavigation(route) { const item = this.menuItems.flatMap((group) => group.items || []).find((candidate) => candidate.route === route); if (!item) return; if (item.target_type === "Page") frappe.set_route(item.target); else if (item.target_type === "Report") frappe.set_route("query-report", item.target); else if (item.target_type === "DocType") frappe.set_route("List", item.target); else if (item.target) window.location.href = item.target; },
	},
};
</script>
<style scoped>
.project-page{display:grid;gap:16px;padding:18px}.project-hero,.panel-head{display:flex;justify-content:space-between;gap:16px;align-items:flex-start}.project-eyebrow{font-size:12px;text-transform:uppercase;letter-spacing:.08em;opacity:.7}.hero-actions{display:flex;gap:8px;flex-wrap:wrap}.project-panel,.metric-card,.accounting-note,.scope-note{border:1px solid var(--border-color);border-radius:12px;padding:16px;background:var(--card-bg)}.filter-grid,.project-cards,.summary-grid{display:grid;gap:12px}.filter-grid{grid-template-columns:minmax(260px,1fr) minmax(180px,.5fr) auto;align-items:end}.project-cards{grid-template-columns:repeat(auto-fit,minmax(160px,1fr))}.summary-grid{grid-template-columns:repeat(auto-fit,minmax(180px,1fr))}.metric-card span,.summary-grid span{display:block;font-size:12px;opacity:.7}.metric-card strong{display:block;font-size:20px;margin-top:6px}.summary-grid strong{display:block;margin-top:4px}.table-wrap{overflow:auto}.project-table{width:100%;border-collapse:collapse}.project-table th,.project-table td{padding:10px;border-bottom:1px solid var(--border-color);text-align:left;vertical-align:top}.project-table .num{text-align:right}.link-button{background:none;border:0;padding:0;color:var(--primary);cursor:pointer}.project-error{padding:12px;border-radius:8px;background:var(--alert-bg-danger);color:var(--text-color)}.project-state{padding:18px;text-align:center;opacity:.7}.accounting-note,.scope-note,.panel-note{font-size:13px}.panel-note{margin:12px 0 0;opacity:.75}.filter-action{padding-bottom:1px}@media(max-width:800px){.project-hero,.panel-head{flex-direction:column}.filter-grid{grid-template-columns:1fr}.hero-actions{width:100%}}
</style>