<template>
	<div v-if="!edgeUIValid" class="history-fallback"><strong>Supplier Quotation History could not start.</strong><span>Required interface components are unavailable.</span></div>
	<EdgeAppShell v-else product="RetailEdge" title="Supplier Quotation History" :tenantName="tenantName" :branchName="branchName" :userName="userName" :menuItems="menuItems" activeRoute="/app/supplier-quotation-history" :hideNativeSidebar="true" @navigate="handleNavigation">
		<EdgePageLayout class="history-page">
			<EdgePageHeader title="Supplier Quotation History" description="Review supplier quotations on a persistent paginated page. Prepare a Purchase Order through the focused governed transaction flow." />
			<section class="edge-panel history-controls">
				<div class="filter-grid">
					<EdgeLinkField v-model="filters.company" label="Company" required placeholder="Search company" :searcher="companySearch" @select="onCompanySelected" />
					<EdgeLinkField v-model="filters.branch" label="Branch" placeholder="All permitted branches" :searcher="branchSearch" @select="onBranchSelected" @clear="clearBranch" />
					<EdgeLinkField v-model="filters.supplier" label="Supplier" placeholder="All suppliers" :searcher="supplierSearch" @select="onSupplierSelected" @clear="clearSupplier" />
					<label class="history-input"><span>Search</span><input v-model="filters.search" type="search" placeholder="Quotation, supplier or reference" @keyup.enter="applyFilters" /></label>
				</div>
				<div class="control-actions"><button type="button" class="edge-button edge-button--primary" :disabled="loading || !filters.company" @click="applyFilters">{{ loading ? "Refreshing…" : "Apply Filters" }}</button><button type="button" class="edge-button" @click="backToPurchasing">Back to Purchasing</button></div>
			</section>
			<EdgeLoadingState v-if="loading && !loaded" message="Loading Supplier Quotations..." :skeleton="true" />
			<EdgeErrorState v-else-if="error && !loaded" title="Supplier Quotation history unavailable" :message="error" @retry="applyFilters" />
			<section v-else class="edge-panel history-list">
				<div v-if="error" class="inline-error" role="alert">{{ error }}</div>
				<div class="scope"><span><strong>Company:</strong> {{ history.company || filters.company || "—" }}</span><span><strong>Branch:</strong> {{ history.branch || "All permitted" }}</span><span><strong>Supplier:</strong> {{ history.supplier || "All suppliers" }}</span><span><strong>Loaded:</strong> {{ rows.length }}</span></div>
				<p class="note">Restricted users see only quotations attributable to permitted RFQs when Supplier Quotation has no Branch field.</p>
				<EdgeEmptyState v-if="!rows.length" title="No Supplier Quotations" description="No permission-visible Supplier Quotations match the selected scope." />
				<div v-else class="table-responsive"><table class="table history-table"><thead><tr><th>Quotation</th><th>Date</th><th>Supplier</th><th>RFQ</th><th>Branch</th><th class="num">Total</th><th>Valid Till</th><th>Status</th><th>Actions</th></tr></thead><tbody>
					<tr v-for="row in rows" :key="row.name"><td><strong>{{ row.name }}</strong><small v-if="row.quotation_number">Supplier ref: {{ row.quotation_number }}</small></td><td>{{ formatDate(row.transaction_date) }}</td><td>{{ row.supplier_name || row.supplier }}</td><td>{{ (row.request_for_quotations || []).join(", ") || "—" }}</td><td>{{ row.branch || "—" }}</td><td class="num">{{ formatMoney(row.grand_total,row.currency) }}</td><td>{{ formatDate(row.valid_till) }}</td><td>{{ row.status || statusLabel(row.docstatus) }}</td><td><div class="row-actions"><button v-if="canPreparePurchaseOrder(row)" type="button" class="edge-small-button edge-small-button--primary" @click="preparePurchaseOrder(row)">Prepare PO</button><button v-if="canUseNativeDesk" type="button" class="edge-small-button" @click="openAdvanced(row.name)">Advanced: ERPNext</button></div></td></tr>
				</tbody></table></div>
				<div class="pagination"><span>{{ history.has_more ? "More Supplier Quotations are available." : (rows.length ? "End of matching Supplier Quotations." : "") }}</span><button v-if="history.has_more" type="button" class="edge-button edge-button--primary" :disabled="loadingMore" @click="loadMore">{{ loadingMore ? "Loading…" : "Load More" }}</button></div>
			</section>
		</EdgePageLayout>
	</EdgeAppShell>
</template>
<script>
const HISTORY_METHOD="retailedge.professional_supplier_quotation.get_supplier_quotation_history";
const SEARCH_METHOD="retailedge.professional_purchasing.search_professional_purchasing_options";
const PAGE_SIZE=40;
const REQUIRED=["EdgeAppShell","EdgePageLayout","EdgePageHeader","EdgeLinkField","EdgeLoadingState","EdgeErrorState","EdgeEmptyState"];
function runtime(){return window.EdgeSuiteUI?.components||{};} function callMethod(method,args={}){return new Promise((resolve,reject)=>frappe.call({method,args,callback:r=>resolve(r.message||{}),error:reject}));} function err(error,fallback){return error?.message||error?.exc||error?._server_messages||fallback;}
export default{
	name:"SupplierQuotationHistoryPage",components:Object.fromEntries(REQUIRED.map(name=>[name,runtime()[name]])),
	data(){return{edgeUIValid:true,tenantName:"",branchName:"",userName:"",menuItems:[],canUseNativeDesk:false,loading:false,loadingMore:false,loaded:false,error:"",filters:{company:"",branch:"",supplier:"",search:""},history:{rows:[],has_more:false,next_start:0,can_create_purchase_order:false}};},
	computed:{rows(){return Array.isArray(this.history.rows)?this.history.rows:[];}},created(){this.edgeUIValid=REQUIRED.every(name=>Boolean(runtime()[name]));},mounted(){if(this.edgeUIValid)this.loadShellAndHistory();},
	methods:{
		async loadShellAndHistory(){try{const[context,operating]=await Promise.all([callMethod("retailedge.edgesuite_ui.get_retailedge_business_hub_context"),callMethod("retailedge.operating_context.get_operating_context")]);const shell=context.context||{};this.tenantName=operating.company_label||operating.company||shell.company||"";this.branchName=operating.branch||"";this.userName=shell.user_name||shell.user||"";this.canUseNativeDesk=Boolean(context?.access?.can_use_native_desk);this.menuItems=this.mapNavigationGroups(context.navigation_groups||[]);this.filters.company=operating.company||shell.company||"";this.filters.branch=operating.branch||"";}catch(_error){}await this.applyFilters();},
		fetchPage(start=0){return callMethod(HISTORY_METHOD,{company:this.filters.company||null,branch:this.filters.branch||null,supplier:this.filters.supplier||null,search:this.filters.search||null,start,page_length:PAGE_SIZE});},
		async applyFilters(){if(this.loading)return;this.loading=true;this.error="";try{const result=await this.fetchPage(0);this.history={...(result||{}),rows:result?.rows||[]};if(!this.filters.company)this.filters.company=result.company||"";if(!this.filters.branch&&result.branch)this.filters.branch=result.branch;this.loaded=true;}catch(error){this.error=err(error,"Unable to load Supplier Quotation history.");}finally{this.loading=false;}},
		async loadMore(){if(this.loadingMore||!this.history.has_more)return;this.loadingMore=true;try{const result=await this.fetchPage(Number(this.history.next_start||this.rows.length));const seen=new Set(this.rows.map(r=>r.name));this.history={...this.history,...result,rows:[...this.rows,...(result.rows||[]).filter(r=>!seen.has(r.name))]};}catch(error){this.error=err(error,"Unable to load more Supplier Quotations.");}finally{this.loadingMore=false;}},
		async searchOptions(kind,txt){const result=await callMethod(SEARCH_METHOD,{kind,txt,company:this.filters.company||null});return Array.isArray(result)?result:[];},companySearch(txt){return this.searchOptions("company",txt);},branchSearch(txt){return this.searchOptions("branch",txt);},supplierSearch(txt){return this.searchOptions("supplier",txt);},
		onCompanySelected(option){this.filters.company=option.value;this.filters.branch="";this.filters.supplier="";this.applyFilters();},onBranchSelected(option){this.filters.branch=option.value;this.applyFilters();},clearBranch(){this.filters.branch="";this.applyFilters();},onSupplierSelected(option){this.filters.supplier=option.value;this.applyFilters();},clearSupplier(){this.filters.supplier="";this.applyFilters();},
		canPreparePurchaseOrder(row){const status=String(row?.status||"");return Boolean(this.history.can_create_purchase_order)&&Number(row?.docstatus||0)===1&&!["Cancelled","Stopped","Expired"].includes(status);},
		preparePurchaseOrder(row){if(!this.canPreparePurchaseOrder(row))return;window.retailedgeProfessionalPurchasingTarget={user:frappe.session?.user||"",action:"supplier-quotation-purchase-order",source_name:row.name,createdAt:Date.now()};frappe.set_route("professional-purchasing");},
		openAdvanced(name){if(this.canUseNativeDesk&&name)frappe.set_route("Form","Supplier Quotation",name);},backToPurchasing(){frappe.set_route("professional-purchasing");},statusLabel(v){return Number(v)===1?"Submitted":Number(v)===2?"Cancelled":"Draft";},formatDate(v){return v?frappe.datetime.str_to_user(v):"—";},formatMoney(value,currency){try{return format_currency(Number(value||0),currency||frappe.boot?.sysdefaults?.currency||"");}catch(_error){return `${currency||""} ${Number(value||0).toLocaleString()}`.trim();}},
		mapNavigationGroups(groups){return(groups||[]).map(g=>({...g,items:(g.items||[]).map(i=>({...i,route:this.routeForItem(i)}))}));},routeForItem(i){if(i.target_type==="Page")return `/app/${i.target}`;if(i.target_type==="Report")return `/app/query-report/${encodeURIComponent(i.target)}`;if(i.target_type==="DocType")return `/app/${String(i.target||"").toLowerCase().replace(/\s+/g,"-")}`;return i.target||"";},handleNavigation(route){const i=this.menuItems.flatMap(g=>g.items||[]).find(x=>x.route===route);if(!i)return;if((i.target_type==="Report"||i.target_type==="DocType")&&!this.canUseNativeDesk)return;if(i.target_type==="Page")frappe.set_route(i.target);else if(i.target_type==="Report")frappe.set_route("query-report",i.target);else if(i.target_type==="DocType")frappe.set_route("List",i.target);}
	}
};
</script>
<style scoped>
.history-page{min-height:100%;display:grid;gap:1rem}.history-fallback,.edge-panel{border:1px solid var(--edge-border,#d9d9d9);border-radius:10px;background:var(--edge-surface,#fff)}.history-fallback{margin:20px;padding:24px;display:grid;gap:8px}.history-controls,.history-list{padding:18px}.filter-grid{display:grid;grid-template-columns:repeat(4,minmax(160px,1fr));gap:.75rem}.history-input{display:grid;gap:.35rem;font-size:.8rem;font-weight:600;color:var(--edge-text-muted,#667085)}.history-input input{min-height:40px;border:1px solid var(--edge-border,#d9d9d9);border-radius:8px;padding:0 .7rem;background:inherit;color:inherit}.control-actions,.row-actions,.scope,.pagination{display:flex;gap:.55rem;flex-wrap:wrap;align-items:center}.control-actions{margin-top:.8rem}.scope{margin-bottom:.4rem;font-size:.82rem;color:var(--edge-text-muted,#667085)}.note{margin:.2rem 0 .8rem;color:var(--edge-text-muted,#667085);font-size:.8rem}.inline-error{padding:.65rem;border:1px solid var(--red-400,#f04438);border-radius:8px;color:var(--red-700,#b42318);margin-bottom:.7rem}.table-responsive{overflow:auto}.history-table{min-width:1100px;width:100%}.history-table small{display:block;color:var(--edge-text-muted,#667085)}.num{text-align:right}.pagination{justify-content:space-between;margin-top:1rem}.edge-button,.edge-small-button{border:1px solid var(--edge-border,#d9d9d9);border-radius:8px;background:var(--edge-surface,#fff);color:inherit;font-weight:600;cursor:pointer}.edge-button{min-height:38px;padding:0 12px}.edge-small-button{min-height:30px;padding:0 9px;white-space:nowrap}.edge-button--primary,.edge-small-button--primary{background:var(--edge-primary,#0f766e);border-color:var(--edge-primary,#0f766e);color:#fff}button:disabled{opacity:.55;cursor:not-allowed}@media(max-width:900px){.filter-grid{grid-template-columns:repeat(2,minmax(160px,1fr))}}@media(max-width:560px){.filter-grid{grid-template-columns:1fr}}
</style>
